# Generated by Django 5.1.5 on 2025-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(max_length=50),
        ),
    ]
