# Generated by Django 5.1.5 on 2025-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sentimentreview_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentreview',
            name='sentiment',
            field=models.CharField(max_length=50),
        ),
    ]
